#ifndef SSL_OBSERVER_MAIN_H_

#if defined(OS_WIN)
#include <SDKDDKVer.h>
#include <WinSock2.h>
#include <wincrypt.h>
#include <Shlwapi.h>
#include <UrlMon.h>
#include <atlconv.h>
#include <winhttp.h>
#pragma comment(lib,"urlmon.lib")
#pragma comment(lib,"ws2_32.lib")
#pragma comment(lib,"Gdi32.lib")
#pragma comment(lib,"Advapi32.lib")
#pragma comment(lib,"winhttp.lib")
#pragma comment(lib,"Ole32.lib")
#pragma comment(lib,"user32.lib")
#pragma comment(lib,"libeay32.lib")
#pragma comment(lib,"ssleay32.lib")
#pragma comment(lib,"zlibstat.lib")
#pragma comment(lib,"Crypt32.lib")
#pragma comment(lib,"Cryptnet.lib")
#pragma comment(lib,"Shlwapi.lib")
#pragma comment(lib,"libevent.lib")
#pragma comment(lib,"libevent_core.lib")
#pragma comment(lib,"libevent_extras.lib")
#pragma comment(lib,"base.lib")
#pragma comment(lib,"googleurl.lib")
#pragma comment(lib,"icuuc.lib")
#pragma comment(linker,"/NODEFAULTLIB:library")
#endif
#include <tchar.h>
#include <cstdio>
#include <cstdint>
#include <cwchar>
#include <process.h>
#include <string>
#include <chrono>
#include <thread>
#include <fstream>
#include <vector>
#include <list>
#include <iosfwd>
#include <sstream>
#include <iomanip>
#include <functional>
#include <openssl/crypto.h>
#include <openssl/err.h>
#include <openssl/x509.h>
#include <openssl/x509v3.h>
#include <openssl/pem.h>
#include <openssl/rand.h>
#include <openssl/ocsp.h>
#include <openssl/ossl_typ.h>
#include <openssl/pkcs12.h> 
#include "event2/bufferevent.h"
#include "event2/buffer.h"
#include "event2/buffer_compat.h"
#include "event2/listener.h"
#include "event2/event.h"
#include "event2/event_compat.h"
#include "event2/http.h"
#include "event2/http_struct.h"
#include "event2/http_compat.h"
#include "event2/keyvalq_struct.h"
#include <plog/Log.h>

#endif